Add quickhull3D's dependencies explicitly
There's only one, luckily! Since it's not a module, jlink doesn't include its
dependencies by default. Without these lines, we get this error, but only at
runtime!:

    java.lang.ExceptionInInitializerError: Exception java.lang.IllegalAccessError: class com.github.quickhull3d.QuickHull3D (in module edu.umich.soar.svsviewer.merged.module) cannot access class org.slf4j.LoggerFactory (in module org.slf4j) because module edu.umich.soar.svsviewer.merged.module does not read module org.slf4j